App/urls.py
from django.urls import path
from App import views

urlpatterns = [

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='index'
    ),

    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    )
]

gameoverweb/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('App.urls', 'App'), namespace='App')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

urlpatterns = [

  
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),


    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    )

]

App/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} by @{}'.format(self.title, self.user.username)

users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

App/forms.py
from django import forms
from App.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('user', 'profile', 'title', 'photo')

users/forms.py
"""User forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):

    username = forms.CharField(label=False,min_length=4, max_length=50,widget = forms.TextInput(attrs={'placeholder':'username','class': 'form-control','required': True}))

    password = forms.CharField(
        label=False,
        max_length=70,
        widget=forms.PasswordInput(attrs={'placeholder':'password','class': 'form-control','required': True})
    )
    password_confirmation = forms.CharField(
        label=False,
        max_length=70,
        widget=forms.PasswordInput(attrs={'placeholder':'password confirmation','class': 'form-control','required': True})
    )

    first_name = forms.CharField(label=False,min_length=2, max_length=50,widget = forms.TextInput(attrs={'placeholder':'first name','class': 'form-control','required': True}))
    last_name = forms.CharField(label=False,min_length=2, max_length=50,widget = forms.TextInput(attrs={'placeholder':'last name','class': 'form-control','required': True}))

    email = forms.CharField(
        label=False,
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(attrs={'placeholder':'email','class': 'form-control','required': True})
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

App/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView

from App.forms import PostForm
from App.models import Post


class PostsFeedView(LoginRequiredMixin, ListView):
    template_name = 'App/index.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 5
    context_object_name = 'posts'


class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = 'App/detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'


class CreatePostView(LoginRequiredMixin, CreateView):
    template_name = 'App/new.hTml'
    form_class = PostForm
    success_url = reverse_lazy('App:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth.models import User
from App.models import Post
from users.models import Profile
from users.forms import SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})


class LoginView(auth_views.LoginView):
    redirect_authenticated_user = True
    template_name = 'users/login.html'
   

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):

    template_name = 'users/logged_out.html'

templates/App/detail.html
{% extends "layout.html" %}

{% block head_content %}
    <title>GameOverWeb</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row">
            {% include "App/game_card.html" %}
        </div>
    </div>

{% endblock %}

templates/App/game_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1 text-light">
        <a href="{% url "users:detail" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>

    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

    
    <p class="ml-2 mt-0 mb-2 text-light">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
</div>

templates/App/index.html
mi pagina repro papi

templates/App/new.html
{% extends "layout.html" %}

{% block head_content %}
<title>Post your game</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4 text-light" >New Game</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label class="text-light">Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success  btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/css.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top " id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "App:index" %}">
            <img src="{% static "img/icon.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav justify-content-end ml-auto">

                <li class="nav-item ">
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" width="35" class="d-inline-block align-top rounded-circle"/>
                        {% else%}
                            <img src="{% static 'img/default-profile.png' %}" height="35" width="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "App:create" %}">
                        <i class="fas fa-plus-square " style="color:#FFFFFF; width:6; height:6;"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-door-open" style="color:#FFFFFF; width:6; height:6;"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/users/detail.html
{% extends "layout.html" %}

{% block head_content %}
<title>@{{ user.username }} | GameOverWeb</title>
{% endblock %}

{% block container %}

    <div class="container mb-5  " style="margin-top: 8em; ; padding: 15px; background-color: black; border: 1px solid white; ">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center" style="padding: 25px; ">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded"
                    width="150px"
                    height="150px"
                />
            </div>

            <div class="col-sm-8 text-light ">
                <h2 style="font-weight: 100;" >
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-success "
                        >
                            Edit profile
                        </a>
                    
                    {% endif %}
                </h2>

                
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p> Web site</p>
                        <a href={{ user.profile.website }} > {{ user.profile.website }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container  rounded" id="user-posts" >
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url "App:detail" post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/ccsuser.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100 ">
        <div class="row h-100 justify-content-center align-items-center ">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5 " id="auth-container">

                <img src="{% static "img/icon.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/login.html
{% extends "users/layout.html" %}

{% block head_content %}
<title>GameOverWeb sign in</title>
{% endblock%}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger">
            Your username and password didn't match. Please try again.
        </p>
    {% endif%}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>


        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>

    </form>

    <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>

{% endblock %}

templates/users/profile.html
{% extends "layout.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container text-light">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{ error }}
                </div>
                {% endfor %}

                <hr><br>

                {# Website field #}
                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                        type="text"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Biography field #}
                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                        class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography"
                    >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Phone number field #}
                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <button type="submit" class="btn btn-success btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/signup.html
{% extends "users/layout.html" %}

{% block head_content %}
<title>GameOverWeb sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}